### ISSUE TITLE
Access violation in glbinding.dll

### ISSUE THREAD

**Issue by Vormeph** [hpicgs/glbinding#103]
I tried glbinding on Ubuntu 14.04 and compiled it with cmake. Everything works and it's really great, so heads up on that! On Windows 8.1 64-bit and through Visual Studio 2013, I compiled glbinding for 64-bit and all went well. I transferred my source files to a Visual Studio project solution and included and linked glbinding, and I've added the appropriate dlls to the folder the .exe file is in; but I get a strange error. Visual Studio throws an exception whenever I try to run my program, and it then says that the source of the exception is from glbinding.dll. At first I thought there was a problem on my end, but the code features nothing detrimental. I therefore compiled glbinding.dll again and readded it to the project, but I still get the same errors. It keeps giving me exceptions after exceptions with 'Access Violation Reading location 0xFFFFF...'. I compiled my program through both Debug and Release modes - the same issue remains. 

What's going on here, how can I fix it; and is it possible that a pre-compiled version of glbinding be made available? Are there certain compiler options I should be enabling on cmake?

**Comment by scheibel** [comment]
Your error description sounds rather strange and we have several users with your configuration that have no problem using glbinding.
If you want to try a pre-compiled version, the one for Windows 8.1 64-Bit and MSVC12 (Visual Studio 2013 Update 3) is available here: https://github.com/hpicgs/glbinding/releases/tag/v1.1.0

**Comment by sbusch42** [comment]
I suggest you have a look at your compiler options and determine if you use the exact same runtime library glbinding is built with. The errors you are describing smell like a runtime-library mismatch. The compiler and linker flags used to build glbinding can be found in the file cmake/PlatformWindowsMSVC.cmake.

**Comment by Vormeph** [comment]
Thanks people, there were OpenGL mismatches since my laptop only supports 4.0; my computer supports 4.3. I used your pre-compiled libraries and now my program runs. Thanks!
