### ISSUE TITLE
GL_NONE_BIT for all bitfield groups

### ISSUE THREAD

**Issue by scheibel** [hpicgs/glbinding#59]

**Comment by cgcostume** [comment]
can you please provide a description/reasoning for this

**Comment by scheibel** [comment]
Currently, none of the OpenGL bitfield types have a defined ```0``` value associated within their bitfield group.
During the first iterations, we introduced ```PathFontStyle::GL_NONE_BIT``` as a manually fix within our xml parsing.

It seams that in the OpenGL specification, each group has an implicit ```0``` value that is usable in each single bitfield group.
Since it is only implicitly defined and we want to support full type safety, we should model it explicitly for all the bitfield groups and not just for ```PathFontStyle```.

**Comment by scheibel** [comment]
I will close this for now as I can't find any example where a ```0``` value is actually used.
I will revert the ```GL_NONE_BIT``` of ```PathFontStyle``` as well.
We can reintegrate it again if the need arises.

**Comment by j-o** [comment]
Please reopen. Here's an example: your basic static data buffer (e.g., vertex buffer) using immutable storage, i.e., `glBufferStorage`. As I understand it, passing 0 to `glBufferStorage` is somewhat equivalent to passing `GL_STATIC_DRAW` to `glBufferData`.
From https://www.opengl.org/wiki/Buffer_Object#Immutable_Storage:
> Static data buffers: In some cases, data stored in a buffer object will not be changed once it is uploaded. For example, vertex data can be static: set once and used many times.
>
> For these cases, you set flags​ to 0 and use data​ as the initial upload

**Comment by scheibel** [comment]
If there is a predefined and semantically meaningful constant provided by OpenGL (in yuzr example, ```GL_STATIC_DRAW```) then we don't want to allow *hacks* that are possible in standard C/C++ with standard OpenGL bindings due to missing type semantics.

Either way, your example doesn't use ```GLbitfield``` but ```GLenum``` so this is completely unrelated and I couldn't find any sources that demonstrates or documents your example.

**Comment by j-o** [comment]
You misunterstood me. `GL_STATIC_DRAW` is an enum constant valid for the (old) `glBufferData` function:
```c++
void glBufferData(GLenum  target,  GLsizeiptr  size,  const GLvoid *  data,  GLenum  usage);
```
The (new in OpenGL 4.4) `glBufferStorage` function indeed takes a `GLbitfield` value for its `flags` argument:
```c++
void glBufferStorage(GLenum target​, GLsizeiptr size​, const GLvoid * data​, GLbitfield flags​);
```
see: https://www.opengl.org/sdk/docs/man/html/glBufferStorage.xhtml

Now let's assume I have some static vertex data I want to upload once and draw many times. Then the classic way (with mutable storage) to do this would be:
```c++
std::vector<glm::vec4> data = ...;
glBufferData(GL_VERTEX_BUFFER, data.size() * sizeof(glm::vec4), data.data(), GL_STATIC_DRAW);
```

If I want to use immutable storage instead (as recommended), the equivalent would be:
```c++
std::vector<glm::vec4> data = ...;
glBufferStorage(GL_VERTEX_BUFFER, data.size() * sizeof(glm::vec4), data.data(), 0);
```

If you don't believe me, please read the article in the OpenGL wiki linked in my previous comment, especially the section about immutable storage. It explicitly states two applications for passing 0 as value for `flags` argument to `glBufferStorage`.

**Comment by scheibel** [comment]
I remember your example but I could no longer find any source.
If this is really possible, maybe we should add the null flag for this one.
