### ISSUE TITLE
global namespace pollution

### ISSUE THREAD

**Issue by p2rkw** [hpicgs/glbinding#71]
In files glbinding/include/glbinding/Function.h and other unnamed namespaces are used, so all classes declared insde are in fact global, because it's header file included from gl*.h.
I think such helper classes shouldn't pollute global namespace.
I just had compilation error because of this issue.

**Comment by scheibel** [comment]
Thanks for reporting, this is actually a bug and will be fixed.

**Comment by cgcostume** [comment]
the tag 1.0.5 was updated, and now includes today's fixes
