### ISSUE TITLE
Duplicated 'revision' file

### ISSUE THREAD

**Issue by p2rkw** [hpicgs/glbinding#72]
Hi,
I just built glbinding with:
```
mkdir build-release
cd build-release
cmake .. # I used ccmake, but it doesn't matter now
make
make pack
```
I tried to install generated packages with
```
sudo dpkg -i glbinding-1.0.5-dev.deb glbinding-1.0.5-runtime.deb 
```
but dpkg complains that there's conflict because glbinding-runtime.deb tries to overwrite file `/usr/share/glbinding/revision` which belongs to glbinding-dev.deb

Edit: It can be fixed with `--force-overwrite` option added to dpkg invocation, but I think it's not the way.

**Comment by scheibel** [comment]
Thanks for reporting.
Theoretically (currently not explicitly), the dev package depends on the runtime package.
This should mean that the dev package only contains files and functionality that isn't provided by the runtime package, including the ```revision``` file.

I think we will fix this soon, but it won't be in a release until 1.0.6.

**Comment by cgcostume** [comment]
this will be fixed shortly:
* for windows we like to provide self-contained archives, so revision file and glbinding.dll needs to be included (this currently also results in wrong determination of installer size for nsis ...)
* for unix systems, the redundant packing will be resolved (glbinding binary and revision file etc. will be included only in the runtime package)
