### ISSUE TITLE
Strongly-typed enums conflicts with regular gl use

### ISSUE THREAD

**Issue by Ryp** [hpicgs/glbinding#74]
Consider this example:
```cpp
GLuint buffer;
GLuint buffer2;
GLsizei size;
void* ptr;
GLbitfield flags = GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT; // Not compiling

glNamedBufferStorage(buffer, size, ptr, flags);
glNamedBufferStorage(buffer2, size, ptr, flags);
```
This isn't allowed by glbinding as far as as I know, due to the lack of conversion of the Mask* types to GLbitfield. But this kind of uses are often encountered in OpenGL code. This problem also arise when wrapping glbinding functions into objects.
```cpp
// OpenGL reference
void glNamedBufferStorage(GLuint buffer, GLsizei size, const void *data, GLbitfield flags);
// glbinding
void glNamedBufferStorage(GLuint buffer, GLsizei size, const void * data, MapBufferUsageMask flags)
```

**Comment by scheibel** [comment]
The actual definition of ```glNamedBufferStorage``` is in fact
```cpp
inline void glNamedBufferStorage(GLuint buffer, GLsizeiptr size, const void * data, MapBufferUsageMask flags)
{
    return glbinding::Binding::NamedBufferStorage(buffer, size, data, flags);
}
```
so as you can see, the third parameter is of type MapBufferUsageMask.
The three mask values ```GL_MAP_WRITE_BIT```, ```GL_MAP_PERSISTENT_BIT```, and ```GL_MAP_COHERENT_BIT``` are all of type ```MapBufferUsageMask``` with some exceptions, where it is actually ```glbinding::SharedBitfield<BufferAccessMask, MapBufferUsageMask>``` because it is shared with ```BufferAccessMask```.
Of course, your above code won't compile because it has invalid parameter conversions in two lines.
First, ```flags``` should be of type ```auto``` so you don't have to actually think about the deduced type for the mask operations (it should be somethink like ```glbinding::SharedBitfield<MapBufferUsageMask>```) and second, our version of ```glNamedBufferStorage``` doesn't accept a ```GLbitfield``` as input but a ```MapBufferUsageMask```.
The ```SharedBitfield``` is convertible to ```MapBufferUsageMask``` and will do so smoothly, but ```GLbitfield``` isn't and shouldn't be.
```GLbitfield``` is mainly existent for OpenGL functions where the API specification doesn't specify a bitfield group and for hacky reasons.

If you want your example code to compile, you have to add ```static_cast```s (or just use type-save bitfields as we modeled and defined them).

**Comment by cgcostume** [comment]
I aggre with @scheibel - glbinding intends to improve opengl programming style and discourage misuse or erroneous use of, e.g., types (https://github.com/hpicgs/glbinding#type-safe-parameters).

For wrapping you can check out [globjects](https://github.com/hpicgs/globjects). In your case, however, the bitfield group ```MapBufferUsageMask``` is wrongly assigned anyway - so we will fixthis  by introducing a new (yet not default) mask for BufferStorage functions (see patch.xml).

**Comment by Ryp** [comment]
I like the direction taken by glbinding in general, however this 'non-conversion' restriction obviously makes all GL wrapper incompatible with glbinding. Too bad, because I dislike GLEW (mainly because of core context creation), but I can't support both GLEW and glbinding in my wrapper without starting to "#ifdef" my code

**Comment by scheibel** [comment]
Sounds like we should provide different glbinding headers for non-typesafe usage :laughing:  (fortunately, a different library is not needed)

**Comment by scheibel** [comment]
We have a look at a convenient solution for this in #108 and #76.

**Comment by Ryp** [comment]
I don't see how #108 is a solution here, since the issue is the lack of conversion between glbinding bitfields and GLbitfields.

**Comment by scheibel** [comment]
I just had a look into this problem. The first case (assigning a typed bitfield to a ```GLbitfield```) is just removing the ```explicit```of the cast operator on ```SharedBitfieldBase``` but the latter is more complicated as enum classes are not allowed to have constructors or cast operators.
I think a complicated workaround with a enum class wrapper may work, but I don't think we will integrate such one soon.

For your specific example it should suffice if you replace ```GLbitfield``` with ```auto```, although this would require C++11.

**Comment by Ryp** [comment]
Thanks for the feedback, indeed that solution seem good enough for what I wanted.
