### ISSUE TITLE
Current master fails to compile on Visual Studio 2013

### ISSUE THREAD

**Issue by j-o** [hpicgs/glbinding#79]
There are several problems:
 - `warning C4244: 'argument' : conversion from 'unsigned __int64' to 'glbinding::RingBuffer<glbinding::logging::BufferType>::SizeType', possible loss of data` (`RingBuffer` uses `SizeType` (=`unsigned int`) in its external interface, but `std::int64_t` internally)
 - `RingBuffer.hpp(93): warning C4127: conditional expression is constant`
 - `RingBuffer.hpp(133): warning C4389: '!=' : signed/unsigned mismatch`
 - `callbacks.cpp(32): error C2797: 'glbinding::FunctionCall::parameters': list initialization inside member initializer list or non-static data member initializer is not implemented`
 - `RingBuffer.h(49): error C2039: 'mutex' : is not a member of 'std'` (missing include)
 - `error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl glbinding::logging::log(bool)" (__imp_?log@logging@glbinding@@YAX_N@Z) referenced in function "void __cdecl compare(void)" (?compare@@YAXXZ)` (and two more)

Warnings must be fixed as well, as they are treated as errors.

Most should be easily fixable, but was there a reason for the first issue?

**Comment by scheibel** [comment]
Fixed with #81.
