### ISSUE TITLE
Per-feature types include

### ISSUE THREAD

**Issue by j-o** [hpicgs/glbinding#80]
Currently, per-feature type declarations only exist in the `functions....h` header, which seems rather large just to get a few type declarations.

**Comment by scheibel** [comment]
I think the main goal is to enable the following code usage:
```cpp
using namespace gl45core;
// ...
GLuint program = glCreateProgram();
```

instead of:
```cpp
gl::GLuint program = gl45core::glCreateProgram();
```

**Comment by scheibel** [comment]
Or...I didn't get the actual problem you tried to document.

**Comment by j-o** [comment]
I'm using the `gl45core` declarations in my code together with globjects. This often results in code like this:
```c++
#include <glbinding/gl/enum45core.h>

#include <globjects/...>

using namespace gl45core;

globjects::someFunction(GL_SOME_ENUM);
```

Now, if I want to use the type declarations from types.h, this results in:
```c++
#include <glbinding/gl/enum45core.h>
#include <glbinding/gl/types.h>

#include <globjects/...>

using namespace gl45core;

using namespace gl; //  < either this
GLint someVal = ...;

gl::GLint someVal = ...; // < or this

globjects::someFunction(GL_SOME_ENUM, someVal);
```

What I would like is this:
```c++
#include <glbinding/gl/enum45core.h>
#include <glbinding/gl/types45core.h> // < !

#include <globjects/...>

using namespace gl45core;

GLint someVal = ...;

globjects::someFunction(GL_SOME_ENUM, someVal);
```

Currently, instead of the non-existing types45core.h, I could include functions45core.h, which results in ~700 unnecessary function declarations.

**Comment by j-o** [comment]
This is related to #82, where such per-feature type declarations might be necessary as well.

**Comment by cgcostume** [comment]
This solution is not intended by glbinding, since providing multiple feature specific implementations for a, e.g., rendering technique, would require casting of incoming types. We are currently testing to provide all feature functions via function pointers instead of additional functions to prevent argument-dependent name lookups.

**Comment by scheibel** [comment]
Related to #83.
