### ISSUE TITLE
Can not build using clang on Linux

### ISSUE THREAD

**Issue by xythobuz** [hpicgs/glbinding#86]
When trying to build on a Ubuntu Travis-CI worker with clang-3.5, I get many error messages like this:

    In file included from /home/travis/build/xythobuz/OpenRaider/glbinding/source/glbinding/source/Binding.cpp:2:
    In file included from /home/travis/build/xythobuz/OpenRaider/glbinding/source/glbinding/include/glbinding/Binding.h:9:
    /home/travis/build/xythobuz/OpenRaider/glbinding/source/glbinding/include/glbinding/gl/types.h:102:1: error: 
          'hash' defined as a struct template here but previously declared as a
          class template [-Werror,-Wmismatched-tags]
    struct hash<gl::GLenum>
    ^
    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_bvector.h:523:31: note: 
          did you mean struct here?
        template<typename> friend class hash;

I have removed the `-Werror` compiler flag in cmake/PlatformLinuxGCC.cmake as a work-around. That allows me to build the library.

**Comment by scheibel** [comment]
On my Ubuntu 14.04 x64 with a ```clang-3.5``` (```3.5.0-4ubuntu2~trusty2```) everything works just fine without issuing any warning or error.
Can you provide more details about your build system?

Something that seems strange in your posted log is the usage of ```gcc-4.8``` header files.

**Comment by xythobuz** [comment]
I'm on a Travis-CI worker running Ubuntu 12.04 LTS, [here is the build log](https://travis-ci.org/xythobuz/OpenRaider/jobs/54406668). The default compiler shipping with this image is too old to build glbindings or my project, so I'm installing clang 3.5 like this:

    sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
    sudo apt-get -qq -y update
    sudo apt-get install --allow-unauthenticated clang-3.5

And to build glbinding:

    export CC="clang-3.5"
    export CXX="clang++-3.5"
    cmake ..
    make -j4
    sudo make install

The full scripts are [here](https://github.com/xythobuz/OpenRaider/blob/master/cmake/travis_before_install_linux.sh), [here](https://github.com/xythobuz/OpenRaider/blob/master/cmake/travis_install_linux.sh), and [here](https://github.com/xythobuz/OpenRaider/blob/master/cmake/travis_script_linux.sh).

To be honest, I haven't looked at the header paths before and I'm not sure why it's using gcc headers.

**Comment by scheibel** [comment]
I think I found the issue with clang including gcc headers and I'm about to verify it: I think we erroneously use the gnu c++11 standard instead of the standard c++11 one (so it seems that clang uses the headers of gcc for the gnu c++11 version).

**Comment by scheibel** [comment]
It may be that the current master has fixed this issue, could you please try it out?
Maybe you have to additionally install "libc++-dev".

**Comment by xythobuz** [comment]
It works now! And you're right, I had to install libc++-dev.
