### ISSUE TITLE
Shared library on Mac OS X has wrong install name

### ISSUE THREAD

**Issue by xythobuz** [hpicgs/glbinding#87]
I have built and installed glbinding on Mac OS X 10.10.2 with XCode 6.2 and all the default options. However, the install name of the installed library seems wrong:

    $ otool -D /usr/local/lib/libglbinding.dylib
    /usr/local/lib/libglbinding.dylib:
    libglbinding.dylib

The full path should be listed instead of only the filename. The expected output would be:

    $ otool -D /usr/local/lib/libglbinding.dylib
    /usr/local/lib/libglbinding.dylib:
    /usr/local/lib/libglbinding.dylib

As a work-around, one can run this command to fix the install name:

    $ sudo install_name_tool -id /usr/local/lib/libglbinding.dylib /usr/local/lib/libglbinding.dylib

But with the proper cmake settings, this should not be necessary.

Probably related is the following warning from cmake:

    CMake Warning (dev):
      Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
      --help-policy CMP0042" for policy details.  Use the cmake_policy command to
      set the policy and suppress this warning.
    
      MACOSX_RPATH is not specified for the following targets:
    
       glbinding

**Comment by scheibel** [comment]
Thanks for reporting.

We are aware of this issue for some time now (https://github.com/hpicgs/globjects/pull/202) and I hope that we will soon integrate an appropriate fix (as external developers depend on this, now).
