### ISSUE TITLE
Change error checking example in README to not loop callbacks

### ISSUE THREAD

**Issue by jngbsn** [hpicgs/glbinding#90]
I tried to use error checking after-callbacks as shown in the main README, but using a `glGetError()` call in the callback caused it to loop back into the callback. Being new the library, I had no idea why my program became completely unresponsive. After some reading, I found using `Binding::GetError.directCall()` was the correct way to go. 

Maybe the example should be changed so other people don't run into the same issue? Or is this possibly a bug?

**Comment by jngbsn** [comment]
Nevermind the accidental close -_-

**Comment by mrzzzrm** [comment]
Also in the "Example for logging:" it should be ```std::cout << call.function->name() << "(";``` instead of ```std::cout << call.function.name() << "(";```
