### ISSUE TITLE
RingBuffer signed/unsigned mismatch

### ISSUE THREAD

**Issue by JaCzekanski** [hpicgs/glbinding#92]
In file RingBuffer.hpp at line 126 :

    return (pos != head);

When compiling with Visual Studio 2013 it throws warning:

    warning C4389: '!=' : signed/unsigned mismatch

With **Treat Warnings As Errors** option (default: enabled) it fails to compile.

**Comment by scheibel** [comment]
Thanks for reporting, we will fix this.

I just want to make sure we know what your build system is, since we're also using an MSVC2013 compiler and it doesn't throw any warnings and builds glbinding without any problem.
The precise compiler version is MSVC 18.0.30626.0

**Comment by JaCzekanski** [comment]
MSVC 18.00.21005.1

I will update and try again.
