### ISSUE TITLE
Implicit type conversion issues with MinGW_w64

### ISSUE THREAD

**Issue by Morwenn** [hpicgs/glbinding#96]
I tried to compile the library with cmake/make on Widows 8.1 with MinGW_w64 32 bits and the compiler chocked with `-Werror` on an implicit type conveersion issue. Basically, in callbacks.cpp, there is an implicit conversion from `long long int` to `std::size_t` and the compiler isn't happy about it, line 80 and 86:

    std::size_t micros = now_micros.count() % 1000;

To get it to build, I added a `static_cast`, but there may be a more elegant solution to it:

    std::size_t micros = static_cast<std::size_t>(now_micros.count()) % 1000;

**Comment by cgcostume** [comment]
Hi Morwenn, should be fixed in 1.1. branch and master. Thanks a lot for reporting. Please close the issue if it is fixed for you.

**Comment by Morwenn** [comment]
Yes, it fixed it for me. Thank you for the reactivity :)
